# Generated by Django 3.2.3 on 2021-06-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('headline', models.TextField()),
                ('banner', models.ImageField(upload_to='')),
                ('introHead', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('history', models.TextField()),
            ],
        ),
    ]
