# Generated by Django 3.2.3 on 2021-06-03 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='historyImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
