# Generated by Django 3.2.3 on 2021-06-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0002_division_historyimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='division',
            name='historyImage',
        ),
    ]
