# Generated by Django 3.2.3 on 2021-06-04 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0003_remove_division_historyimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('headquarter', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('census1991', models.IntegerField()),
                ('census2001', models.IntegerField()),
                ('census2011', models.IntegerField()),
                ('divisionName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourismBD.division')),
            ],
        ),
    ]
