# Generated by Django 3.2.3 on 2021-06-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0004_district_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_info',
            name='area',
            field=models.FloatField(),
        ),
    ]
