# Generated by Django 3.2.3 on 2021-06-06 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0008_district_travel_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='district_travel',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
