# Generated by Django 3.2.3 on 2021-06-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0009_district_travel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('feedbackText', models.TextField()),
            ],
        ),
    ]
