# Generated by Django 3.2.3 on 2021-08-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0010_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='District_popular_things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('districtName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourismBD.district_info')),
                ('divsion_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourismBD.division')),
            ],
        ),
    ]
