# Generated by Django 3.2.3 on 2021-08-25 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismBD', '0011_district_popular_things'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District_popular_things',
            new_name='District_popular_thing',
        ),
    ]
